### ISSUE TITLE
Do we still need the ant expand creole xml task?

### ISSUE THREAD

**Issue by greenwoodma** [GateNLP/gate-core#1]
The old ant task for fully expanding creole.xml has been superseded by the new maven plugin. Does anyone have any good reason for keeping the ant task?

**Comment by domrout** [comment]
I'd definitely say remove it, because leaving it there can only really be confusing.

**Comment by johann-petrak** [comment]
Do we still keep ant at all (and where?) or are we going to mavenise all builds?

**Comment by greenwoodma** [comment]
Within gate-core there are a couple of ant build.xml files which I've kept for now as they do odd things that might require a custom maven plugin. However it would be nice to remove ant as a transitive dependency of the gate-core artifact. The code contains two custom ant tasks; this one and one for packaging an application. This one is definitely obsolete and the other doesn't support all plugin types so may be fully replaced eventually anyway if people are happy to not be able to do either task directly from ant, but I'll open another issue for the package task if that becomes relevant.
