### ISSUE TITLE
Use latest GATE branding

### ISSUE THREAD

**Issue by greenwoodma** [GateNLP/gate-core#101]

**Comment by greenwoodma** [comment]
as part of this I'm thinking of revamping the about box. The list of contributors is out of date and long and unwieldy. We have a list on the website of alumni and external contributors etc. so I'm thinking of simplifying the about box to list just the current maintainers of gate-core. It's a smaller list and easier to keep up to date across versions. Does anyone have any objections?

**Comment by johann-petrak** [comment]
I am not sure why we need any names in there at all.
The logo, a link to some canonical home page and all the relevent system info would be sufficient in my opinion. 
Maybe also the Organization name and License.

**Comment by greenwoodma** [comment]
not a bad idea actually

**Comment by greenwoodma** [comment]
Turns out I forgot all the icons for the installer which are in `distro/build/deploy`

**Comment by ianroberts** [comment]
Splash screen and icons in `distro/build/deploy` updated in 5a3a7490a071ba230b008fa0b3c2152fa9139d88 - `.png`, `.ico` for both `gate.exe` and the Windows `installer`, and `.icns` for Mac app bundle.
