### ISSUE TITLE
GATE naming

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-core#104]
As an added action to the re-branding, could we perhaps also simplify the names? At some point, the name "GATE Developer" got introduced for the GATE GUI. I never liked that name because it gets too easily associated with programming, which is exactly what the GUI tries to help the user avoid.
Another issue is that long names for the program turn out to be less then optimal in other places, e.g. when the installer creates the icon for the GATE GUI on the desktop: the name there then needs two rows of text and sometimes cannot be show fully even then.

One motivation for "GATE Developer" I think was to find a name for the combination of "GATE Embedded/Core" plus GATE GUI, thinking we might separate those evebtually, which we never will. 

I think we could just refer to "GATE Developer" as "GATE" for places where we want to be concises and as "GATE GUI" where we want to emphasize that we particularly mean the GUI program (and correspondingly "GATE Core" where we just refer to the library).

PS: as you can see I have given up on my proposal to rename GATE to GateNLP to emphasize what it is about and to give it a less generic name and thus make it easier discoverable and separable in search engines, publications etc.

**Comment by greenwoodma** [comment]
after discussion at the team meeting it was agreed that we could drop "Developer" from the shortcuts the installer creates as a shortcut is always going to lead to a GUI not an API and so the lack of the developer keyword isn't going to be misleading. We've kept the window title etc. as "GATE Developer" though to continue to differentiate from the API.
