### ISSUE TITLE
New transparent splash window sometimes looks weird and appears at an odd position

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-core#106]
The new splash window gets shown with a transparent background on my system. Not sure if that is deliberate, but this will look very different depending on the display background a user has. In the worst case the background is green and only the red letters are shown :) -- except for color blind people who will see nothing at all or almost nothing in many background combinations. 

Also the splash window appears on the right edge of my left monitor on my two monitor system. 
This happens with java versions 13 and 15 as well.

**Comment by greenwoodma** [comment]
Yes, I should probably remove the transparency. It wasn't entirely intentional, I just dropped in the new image which happened to be transparent.

The placement is entirely controlled via the JVM though, and I've known this be very odd when you have multiple monitors.
