### ISSUE TITLE
Better tooltips / explanations for those symbols in front of parameter names in the GUI

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-core#110]
Never really gave much thought about these but there are icons in front of:
* parameter names in the init Parameter dialog and runtime parameter dialog (looks like "<?>" )
  There is no tooltip to explain this symbol. It always seems to be the same symbol, so why is it even there? 
* feature names in the Resource features pane and in the feature edit popup. This looks like \subset the mathematical "is subset of" symbol but has tooltip "Custom feature" so is apparently meant to be a C. I have no idea what a custom feature is and never seen anything else there. I do not think "Custom feature" is mentioned anywhere in the user manual either. This icon also has the problem that it is yellow, but sometimes shown with a white background which makes it almost impossible to see. 

I do not really know what these are about, but I think it would be good to either provide better tooltips for both and also make it easier to figure out what they mean (by making the tooltip string or "<?>" or both findable in the manual). 
Or just remove them if they are not communicating important info.

**Comment by greenwoodma** [comment]
the <?> just means it's a value to fill in which I think is fairly self explanatory

the C in the feature dialog (it is a C and not subset, it's just the font that's used that makes it look funny) means the feature is custom in that it isn't restrained by a schema. you get different icons against features when you are doing schema based editing.

**Comment by johann-petrak** [comment]
Well I do not see any purpose whatsoever for the "<?>" icon then. The fact that one can fill in values is normally sufficient to indicate that a it is a value to fill in. So, why not remove it?

And as I said, for the "C": nobody would understand this from looking, but understanding from looking is what icons are for, there is no tooltip, I could not find an explanation in the manual, and the C is both weird and not properly visible against a white background.

Why was this closed?

**Comment by greenwoodma** [comment]
I closed it as there is nothing to fix.

I think removing the <?> icon is more likely to confuse existing users than it is to help new users.

The C icon is described in the tooltip (yes there is a tooltip which labels it a "custom feature") and it makes perfect sense in the context of schema controlled editing.

So as there is nothing to fix within the gate-core repo I closed the issue. If you think they need documenting better (and you possibly have a good argument for that) in the userguide then feel free to open an issue on [it's repo](https://github.com/GateNLP/userguide).

**Comment by johann-petrak** [comment]
I think there are several ways how one could improve the GUI:
* Remove the <?>. It serves no purpose but looks cryptic. I do not see how not having it would confuse anyone. It takes up space that could instead display useful stuff
* Use a better font or graphic to make the c Look like a c, If c(ustom) is really a useful name here (I find it weird that essentially all features not in a schema are called "custom")
* Use a better/darker colour so it is visible on white background
* Alternately, remove and only show an icon for schema defined features only - which I think would be much better still

**Comment by ianroberts** [comment]
> * Use a better font or graphic to make the c Look like a c, If c(ustom) is really a useful name here (I find it weird that essentially all features not in a schema are called "custom")

What would you call it instead?  The three states that need to be distinguished are defined by a schema and required (currently a red "R" icon), defined by a schema but optional (a red "O") or not defined by a schema (the yellow "C").

> * Use a better/darker colour so it is visible on white background

The colour of the background is a function of the L&F, it isn't always white (though in my case on Mac the background is pale yellow, which is possibly worse still). On Nimbus it's a mid grey and on Metal a mid blue so the yellow shows up nicely.
