### ISSUE TITLE
Typing an underscore switches focus from the feature editor to the document

### ISSUE THREAD

**Issue by domrout** [GateNLP/gate-core#15]
This means you can easily type text accidentally into the document

**Comment by greenwoodma** [comment]
I've just tried this and can't reproduce it. Is this specific to Mac or Windows?

I tried an underscore in the annotation name, feature name, and feature value and none cause the focus to switch. I also can't see any reason why it should it's not as if underscore is a control key in any sense. I think there must be something else going on here
