### ISSUE TITLE
OCR support in GATE

### ISSUE THREAD

**Issue by luisenriqueramos1977** [GateNLP/gate-core#158]
Dear All, 

I tested the service of GATE cloud:
https://cloud.gate.ac.uk/shopfront/displayItem/ml-ocr
Which provides the result I need for my application, and I would like to know if it is only available online?, 
or if the code of this app is available as open source?.

Best regards.

Luis Ramos

**Comment by ianroberts** [comment]
Closing as discussion has moved to https://groups.io/g/gate-users/message/1142
