### ISSUE TITLE
Unable to load any plugin: no such file "creole.xml"

### ISSUE THREAD

**Issue by juneMJ** [GateNLP/gate-core#164]
Hello,
I've tried many times with several versions of GATE and on fresh devices, always the same error: 
_~\.m2\repository\uk\ac\gate\plugins\8.5.1\creole.xml (The system cannot find the file specified)
Plugin not available!_
I'm running the installation on Windows 10, downloaded the latest JDK (Java 20 Oracle Corporation on Windows 10).
Knowing that when I try to download the default list it gets empty list, and when I specify the repository location, it gives me the above error.
How to fix this?
Thanks!

**Comment by greenwoodma** [comment]
Which version of GATE are you trying to use?

That missing file error, doesn't make any sense to me, as it's looking for a file which would never exist. Did you specify that path yourself in some way?

When you say the default list of plugins is empty, did it try and download the list? Was there any error message shown on the message pane complaining that the download of the list failed?

**Comment by juneMJ** [comment]
I've tried the latest version 9, when it didn't work I tried a previous version 8.5.
The empty list comes with this error:
_Unable to download list of default plugins. Please check your Internet connection and restart GATE_
I checked the connection and changed to a different connection type, nothing worked. Then I found in some documentation that I can specify the repository folder location manually so I did, but I get the error about the creole.xml file.

**Comment by greenwoodma** [comment]
That error about checking your internet connection suggests that GATE can't connect to github.com to download the required metadata file that defines the plugins. The latest version of GATE (v9.0.1) downloads this file https://raw.githubusercontent.com/GateNLP/gate-metadata/master/default-plugins/plugins-9.0.1.tsv -- can you access this file in a web browser? If not that suggests something on your computer or local network is blocking github which will indeed cause issues with the plugin list.

If you can access that file it may be that your computer is configured to use a proxy that somehow GATE isn't seeing. There are details in the userguide about manually configuring the proxy: https://gate.ac.uk/userguide/sec:gettingstarted:launchconfig

**Comment by juneMJ** [comment]
Setting the proxy fixed the problem.
Thank you very much!

**Comment by greenwoodma** [comment]
Perfect!
