### ISSUE TITLE
Initialization/Duplication of some LanguageAnalysers is not thread-safe

### ISSUE THREAD

**Issue by kzn** [GateNLP/gate-core#17]
We use GATE extensively to do NLP document processing. Our software instantiates the processing pipeline from the file system and then duplicates it to use it in multithreading environment.

Some time ago we switched the duplication calls from the sequential to parallel (using ExecutorService). And we started to experience some infrequent random errors.
After some investigation we found that some GATE internal and external resources are using unsynchronized primitive ints as internal counters (e.g. indexes of FSM states).

This results in eventual errors in concurrent initialization or duplication.
The incomplete list of affected classes:
gate/creole/tokeniser/SimpleTokeniser.java:  public static int maxTypeId;
gate/creole/tokeniser/FSMState.java:  static int index;
gate/creole/tokeniser/DFSMState.java:  static int index;
gate/creole/gazetteer/FSMState.java:  private static int index;
gate/jape/SinglePhaseTransducer.java.caching:    public static int avesize = 0;
gate/jape/SinglePhaseTransducer.java.caching:    public static int maxsize = 0;
gate/jape/SinglePhaseTransducer.java.caching:    public static int avecount = 0;
gate/fsm/State.java:  protected static int index = 0;
gate/fsm/Transition.java:  private static int index = 0;

**Comment by greenwoodma** [comment]
I'm not quite sure I fully understand how your duplication works, but as far as I can tell all the variables you refer to are only accessed read-only once the PR has initially been created. This means they are safe to access across threads and so are not handled in any special way by the built in GATE duplication code, i.e. a call to Factory.duplicate(Resource)

All I can think of is that you aren't allowing initialisation of the PR to fully complete before you attempt to duplicate it, thus ending up with multiple threads attempting to write to the static fields.

Could you provide a simple example that shows how you duplicate so I can double check I haven't missed anything obvious?

**Comment by kzn** [comment]
We call gate.Factory.duplicate() from different threads to speedup the whole initialization. But it is not the cause of the problem.

The problem arises when you try to instantiate, say two independent JAPE transducers from different threads. If those threads arrive simultaneously to the FSM construction code and start to create gate.fsm.State objects. 

Those objects have an internal index stored in the gate.fsm.State.myIndex field. This field is assigned within the constructor of the gate.fsm.State which simply increments the static counter gate.fsm.State.index. So you could experience the race condition on this index.

The effect is that occasionally you get  States with same myIndex **within** one FSM.

**Comment by greenwoodma** [comment]
Ah I see. I got distracted by the fact you mentioned duplication, whereas this could occur if you simply create two JAPE instances from different grammars in two threads at the same time (for example).

The problem here is that I can't see an easy fix. Yes we could change the plugins we develop to behave differently (and we might) but in the general case you could be using plugins from numerous sources any of which could suffer from this problem and I can't see how we would prevent the race condition from happening, except by making Factory.createResource() synchronized, but that seems like overkill.

The only thing I can suggest for now would be to switch back to loading apps in sequence, but I'll leave the issue open for now to force us to think about it further

**Comment by kzn** [comment]
Maybe the User Guide should state explicitly that a plugin initialization code is expected to be thread-safe? 
Or maybe create an marker interface that indicates that this Resource could be instantiated in thread-safe manner?

As usual, it is easier to make suggestions, than to implement them.

**Comment by ianroberts** [comment]
It's more subtle than just "thread-safe" - that phrase usually means that the code can cope with several threads calling methods on the same object instance at the same time, which doesn't happen with Resource `init` methods (any one instance's `init` is guaranteed to be called exactly once).  The issue here is interference through static state when _different_ objects' `init` methods are called at the same time.

**Comment by kzn** [comment]
Yeah, 'thread-safety' isn't the right term, It is more like 'stateless initialization' or something like that.

**Comment by domrout** [comment]
Why is the JAPE loader using so much static state? Would not the most direct solution be to address this?

Dom

**Comment by ianroberts** [comment]
@domrout yes, the fix for these particular plugins is relatively straightforward (switch a couple of `int` fields to `AtomicInteger` and/or move them to be non-static in a different class).  The question is how many similar issues there are in other plugins that we don't yet know about.

**Comment by domrout** [comment]
I would argue that fixing the particular plugin is a good start, and helpful community testing from users like Mr Kazennikov will help us to identify other issues if they pop up in the future. This is an anti-pattern in general, though, so I can’t imagine it has been used in too many places.

Thanks
Dom

**Comment by greenwoodma** [comment]
unfortunately I have a feeling it's more widespread than we'd like to admit, especially in older plugins when threading wasn't really an issue. I have however added it to our internal notes for updating plugins to 8.5 so hopefully we'll pick up most of the cases during that process. It's also picked up by FindBugs (run automatically on all the new plugins) as ST_WRITE_TO_STATIC_FROM_INSTANCE_METHOD so should be easy to spot on any new plugins as well before it becomes an issue.

**Comment by greenwoodma** [comment]
I've now fixed all the issues in ANNIE (see GateNLP/gateplugin-ANNIE@9287751a0e68b86042b07e06258299e4f7e82b8d for more details) which covers the issues in the original issue report but I'll leave the issue open for now while we check through the other plugins as they make their way into git.

**Comment by greenwoodma** [comment]
I've now fixed all the similar issues in all the plugins recently moved from svn to github. I'll continue to check each plugin as I move them across for this issue. Thanks again for the issue report. I'll close the issue once I've moved all the existing plugins to github.

**Comment by greenwoodma** [comment]
Having now moved all the plugins to github I think we've fixed all the instances of this in our own code, so I'm going to close the issue.
