### ISSUE TITLE
URL for a directory may not get persisted correctly in an xgapp file.

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-core#21]
Had a case where a URL that refers to a directory, set from the filepicker for a runtime parameter of a PR, did not have the trailing slash it should have. So when the URL gets read and set for the runtime parameter it does not have the slash and therefore does not indicate a directory properly. 
Need to investigate how that can happen and if the PersistenceManager is could be swallowing the slash when persisting the URL.

**Comment by greenwoodma** [comment]
Hasn't been seen again, so closing for now, especially as we've replaced some of the code that could have been the problem.
