### ISSUE TITLE
Error handling when loading a maven plugin with invalid creole.xml

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-core#22]
When a mavenised plugin is created with a `creole.xml` file that contains a 
`<JAR scan="yes">I.do.not.exist.jar</JAR>` line, then the plugin appears to load fine but then 
does not work (no resources are shown). The messages on the message tab are all in black and the last message is 

    "CREOLE plugin loaded: ..." 

but among the other messages also appears 

     "java.io.FileNotFoundException: JAR entry I.do.not.exist.jar not found in .... Plugin not available!" 

This is not shown in red and does not throw an exception, apparently.

Any error when loading the `creole.xml` file should show a user friendly message and throw and exception. Since users may make all kinds of small mistakes when setting this up for the new mavenized build of plugins, we have to expect everything that can get wrong to occur at some point.

**Comment by greenwoodma** [comment]
Interesting the error messages you see are dumped to the console via log.error which for some reason in the default config sends everything to stdout, which is why it's printed in black not red, probably should open another issue for that.
