### ISSUE TITLE
Weird window sizing bug after changing dual monitor setup.

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-core#24]
GATE starts with a default window size that has the window height set to a ridiculously low value and thus does not show any content, only the menu and tool button bars (width is ok).
Also there are intermittent/non-reproducible situations where the right-click menu now suddenly goes over two columns, showing e.g. "Applications->run" in the second column. 

This may be related to a new dual monitor configuation on a Linux Ubuntu 17.10 computer with monitor 1 being 1680x1050, normal and monitor 2 being 1920x1080, left-rotated.

As already known for a long time, the splash screen is also in a weird place, but now the location is even weirder (happens to be the bottom right of the left monitor). This is because the coordinates for the splash screen are apparently calculated by summing over the dimensions of both monitors.

**Comment by greenwoodma** [comment]
Which version of Java are you using. This sounds like Swing is getting confused about the monitor sizes and doing something stupid, and I know Java 9 has better support for larger and odd resolutions.

**Comment by johann-petrak** [comment]
This was Oracle Java jdk1.8.0_45. Tested with jdk-9.0.4 and as you said the main window and right click popup windows indeed are back to normal again.

The splash is still in the wrong place, but I think that is due to our own code trying to figure out the coordinates.

**Comment by greenwoodma** [comment]
Good to hear it works better under JDK9. The splash screen is unfortunately completely outside our control as we simply pass the path to the image to the JVM at startup, we don't display or position it explicitly.

**Comment by johann-petrak** [comment]
Ah ok, my mistake, I thought we create the splash screen on our own (which we could, I guess, but I wonder why we even need a splash screen?)
JavaDoc says, and I cite "The position on multi-monitor systems is not specified."  Another bug solved by Sun by simply changing the documentation! 
Probably best to close this as wontfix for now since the workaround for the size problem is using Java 9.

**Comment by johann-petrak** [comment]
WONTFIX
