### ISSUE TITLE
While saving document as inline.xml special characters line & is getting saved as &amp;

### ISSUE THREAD

**Issue by ganeshkaspate** [GateNLP/gate-core#29]
I am using GATE's feature save as inline xml. There when  a document has & or any specia char then it gets saved in different way. So, why is it not the same way when we open any xml in GATE ? I mean its not the exact copy of the document which we see in GATE .

**Comment by ianroberts** [comment]
This is not a bug - `&` characters _must_ be escaped as `&amp;` in order for the output to be well formed XML.
