### ISSUE TITLE
DoubleDT class issues with gate core jar 8.4.1

### ISSUE THREAD

**Issue by parvezatsynerzip** [GateNLP/gate-core#30]
Hi, I am using gate 8.4.1. I am using maven dependency to download gate and it downloads gate-core-8.4.1.jar and a couple of other jars. But these do not have Data type classes including DoubleDT. I see from your installation folder that these classes are there in gate.jar and not gate-core.jar. But there is no info on how to get gate.jar using maven dependency. Could you please help me on this?

**Comment by greenwoodma** [comment]
The `DataType` subclasses are there in gate-core-8.4.1.jar. You can't create new instances of them using a constructor though so to get an instance of `DoubleDT` you would need to call `DataType.getDoubleDataType()`
