### ISSUE TITLE
Document exporter UI default file name logic flawed

### ISSUE THREAD

**Issue by ianroberts** [GateNLP/gate-core#39]
The logic used in `DocumentExportMenu.getSelectedFile` to come up with a suggested file name for the export is flawed in a number of ways, in particular it is badly broken on Windows and mildly broken on other platforms in cases where a directory name contains spaces or other non-alphanumeric characters.

 - Firstly, it does `.getPath()` on a URI or URL and then later assumes it can safely construct a `File` from such a path - this usually works on Mac/Linux but is guaranteed to break on Windows
 - Second, it replaces all characters other than `[/a-zA-Z0-9._-]` _anywhere in the path_ with underscore - this includes the colon of a drive letter on Windows, and any spaces or other non-alnums in any of the parent directory names

The upshot of this is that if you have a document with a `sourceUrl` like `file:/C:/Users/ian/My%20Documents/interesting%20file.txt` it defaults to trying to save it as `C:\C_\Users\ian\My_Documents\interesting_file.xml` (which is definitely not going to be valid).

Even on Mac where there's only one filesystem root and forward slash is the separator, it's still common to use spaces in file and directory names so if you were to load a file from `/Users/ian/GATE Documents/doc 1.txt` the "save as inline XML" would offer `/Users/ian/GATE_Documents/doc_1.xml` as the default target - less bad but still broken.

I would suggest (a) using proper URI manipulation and converting back to `File` using the `new File(URI)` constructor, to properly handle Windows conventions, and (b) only applying the "cleanup" rules on the actual file name (the last component) and not on the ancestor directories.

**Comment by greenwoodma** [comment]
also.... if you create a document from a string and then try and save it, you'll get the name from the previously saved document -- I assume because there is no source URL. This is dangerous as it's east to accidentally overwrite a document
