### ISSUE TITLE
Make it easy and obvious to bring up the documentation for a plugin in the plugin manager

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-core#40]
The plugin manager has access to the the pom `<url></url>` field for the project and it would be good if there would be a button or some other obvious way to display that page which should probably be the main documentation page for that plugin or a page that contains a link to the documentation page. 

A simple way to achieve this may be to chow the actual URL as a clickable link between the description and the list of PRs. 

If at all possible, it would also be cool to allow navigating to the help pages defined for the resources shown in the list, e.g. from a right-click menu or by double clicking.
If the information from the resource annotations is fully available to the resource manager from the meta-info pom, then it would probably also be nice to immediately show the description of the resource in the GUI when a resource is clicked in the list together with a hint about how to show the full help web page.

**Comment by greenwoodma** [comment]
This is on the to-do list. The plugin manager now has a toolbar that appears below the list of resources in a plugin. Currently it only contains the button for extracting resources, but will eventually contain other things, including a button to launch the help pages.

**Comment by johann-petrak** [comment]
The button does not get updated when the user switches from the plugin where it was activated to a different plugin, without selecting again. 

Would there also be a way to have a URL for the plugin as a whole, instead of just each resource related to the plugin?

**Comment by greenwoodma** [comment]
Ah, good spot, I'll have a look at the switching issue.

Unfortunately the plugin itself doesn't have a help URL (I think they did at one point when we had the update sites, but I don't think we pull it out of the pom.xml properly when building the creole.xml so would have to re-release every plugin to get that working). Plus this allows us to handle a plugin with resources that may be documented in different places (i.e. all the ones documented in the user guide where often different tools might be in different sections).

**Comment by greenwoodma** [comment]
fixed the switching issue in 81d16d5
