### ISSUE TITLE
Application upgrade tool creates files with DOS line endings

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-core#42]
It seems the updated pipeline has DOS line endings which also causes the git diff command to show the whole file as changed. 
It would be better to have unix line endings or keep the line endings already there.

**Comment by ianroberts** [comment]
This is the default behaviour of JDOM.  It is possible to override it (by calling `setLineSeparator` on the `Format` object) but we wouldn't know what type of endings were used in the original file unless we first opened it as a text file and checked for line endings before passing it to the XML parser.  I contend that most people wouldn't care, and those who do care will know how to convert files between different line ending styles themselves prior to checking them in.

**Comment by johann-petrak** [comment]
Most xgapp files are the result of writing through the persistence manager so I would have thought the line endings are always what is created there, and at least on linux, those are unix line endings. So the upgrade tool could just do the same. The output of the upgrade tool should ideally match what the persistence manager would have created so that changes are more easy to track. 
I think the preferred solution would probably be for the persistence manager and the upgrade tool to always use the same line-ending convention that should also be used for source files which is unix-style endings.
If this is hard to do it is probably not worth the hassle, but I did not expect it to be hard :)

**Comment by ianroberts** [comment]
Still not perfect because the JDOM serializer does a few syntactic XML things differently compared to the XStream one (adds a space before the `/>` of empty elements, converts `<foo></foo>` to `<foo />`, etc.) but the diffs are a lot more manageable than they were previously.
