### ISSUE TITLE
Busy indicator in the GUI when fetching JARs for loading a pipeline

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-core#43]
When a pipeline is loaded that requires to fetch a number of plugins which are not in the cache yet, there is no indication in the GUI what is happening. Even the busy icon seems to appear only at a later stage. 

It may be less confusing for users to get some message ("Downloading required plugin xx", "Downloading required plugins..") in the bottom message line, or some other indicator for this and maybe also make the usual busy indicator (the turning cogs) appear right from the start?

**Comment by greenwoodma** [comment]
Not quite sure why you don't see it, but I had this very same situation this morning and the cogs were visible from the moment I clicked load, all through the downloading of the jars, until the app was fully available.

**Comment by johann-petrak** [comment]
Originally I noticed this when using one of those temporary maven repositories, which may be a bit slower than the other maven repositories used. 

But here are steps to reproduce which always work in my case:
* Using GATE 8.5 distro
* Have gateplugin-ANNIE (v8.5, but does not matter) checked out somewhere
* Removed/moved `~/.m2`
* Start `gate.sh -tmp` (use -tmp to avoid anything getting loaded from the session, if any)
* Application - restore application from file: load application from gateplugin-`ANNIE/src/main/resources/resources/ANNIE_with_defaults.gapp`

Sometimes the time between clicking load and the cogs starting is short, sometimes longer, but always noticeable (usually 1-2 seconds), I suspect this depends on the speed of the connection to the repository.  With the staging repository, the delay was more in 5 or 6 seconds range for me.
