### ISSUE TITLE
Allow the upgrade tool, when running from a file, to specify non-existing coordinates

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-core#44]
Sometimes it would be very useful to upgrade a bunch of pipelines to correspond to a version
that is yet to be released on Maven, for this purpose it would be useful if one could specify a
version that does not exist in the upgrade tsv file. 
The tool may print a warning in such a case to avoid doing this by accident, or may require some additional parameter or column in the tsv to make this request explicit.

**Comment by greenwoodma** [comment]
This already works, in that the tool uses the same search path as the rest of GATE; your maven cache, our snapshot repo, central, and anything extra defined in your settings.xml. So as long as the plugin is in one of those locations you can use it in the upgrade tool. So if you are increasing the version number of a plugin then as long as you've built it once it will be available in the upgrade tool.

**Comment by johann-petrak** [comment]
Ah cool, I must have done this wrong then!

**Comment by greenwoodma** [comment]
> Ah cool, I must have done this wrong then!

there is always the chance there is a bug, so it might be worth you deliberately testing again at some point, but it's certainly how it should work

**Comment by greenwoodma** [comment]
I've just accidentally tested it worked as I assumed a new version of a plugin Ian pushed for me earlier today had synced to central when it hadn't but the tool offered me it anyway as it's in my local cache.
