### ISSUE TITLE
GUI becomes unresponsive after populating corpus in datastore

### ISSUE THREAD

**Issue by greenwoodma** [GateNLP/gate-core#49]
If you populate a corpus that's in a datastore the GUI goes mad as it adds and removed documents quickly. While this looks odd it's not a huge problem and shows you something is happening. Unfortunately once the populate has finished the resource tree is often left in a mess and quickly becomes unresponsive. AN indication of this is a document icon in the tree with no name. Clicking in the tree then results in NPE's. You can also sometimes get an array out of bounds exception during the population (I assume where we have overlapping adds and removes happening via the listeners).

As an example load the Format Twitter plugin and then populate from the attached tweets, you'll probably end up with a completely borked GUI.

[trump-tweets-2018-06-12-000.gz](https://github.com/GateNLP/gate-core/files/2094108/trump-tweets-2018-06-12-000.gz)

**Comment by greenwoodma** [comment]
I don't have a good solution for this yet. Essentially I think  we need to stop the JTree updating on each model change, when we know we are adding/removing a lot of nodes. One option would be to clone the tree model add to the clone and then switch it back in after the populate. But that seems rather horrible.

Another option would be to prevent the tree model from being updated at all and then rebuild the model from the CreoleRegister after the population has completed.

**Comment by ianroberts** [comment]
Or come up with a way to "debounce" the added/removed events (have the listeners add events to a queue, and then have a background thread clear out the queue every second or so and apply all the pending updates in one operation)

**Comment by ianroberts** [comment]
Also I notice that at some point the `resourceLoaded` event handler in `MainFrame` has been changed to run directly on the calling thread rather than in a `SwingUtilities.invokeLater`, whereas the `resourceUnloaded` still runs on the EDT.  This might be confusing matters if the events are firing on different threads.

**Comment by greenwoodma** [comment]
Yes, that seems to be the problem. I'm not sure why someone (probably me) removed the `SwingUtilities.invokeLater` wrapper in `resourceLoaded`. If you try and populate the datastore with the developer tools plugin loaded it's clear that the update of the UI when a resource is loaded is an EDT violation. Reinstating the move to the EDT appears to fix the problem, hopefully it doesn't mess anything else up; I know that in some cases I removed the `invokeLater` call because the code was already running on the EDT and the extra call caused problems. If we see any odd behaviour around adding items to the resource tree the fix to this issue is likely to be the cause.
