### ISSUE TITLE
SerialController.runComponent leaks listeners

### ISSUE THREAD

**Issue by ianroberts** [GateNLP/gate-core#52]
`SerialController.runComponent` adds progress and status listeners to the PR it is about to run before calling `execute`, but only removes these listeners if `execute` completes successfully.  If `execute` throws an exception then the listeners never get removed.  This is not a problem in normal circumstances, but each document that fails will make subsequent executions of the same PR slightly slower (because the `fireProgressChanged` has to notify more and more listeners each time), and in situations like GCP where you're re-using the same PRs for potentially tens or hundreds of thousands of documents this becomes an issue (I noticed it in an app that uses the realtime controller, where towards the end of the batch _every single document_ failed with a timeout, and of course each timeout failure exacerbates the issue further).

I'm stunned nobody has noticed this before as the code in question has not been changed for many years.

**Comment by greenwoodma** [comment]
ouch!

**Comment by ianroberts** [comment]
Also back-ported to 8.4 maintenance (https://sourceforge.net/p/gate/code/20290/)
