### ISSUE TITLE
No error message when loading of plugin through Plugin Manager fails

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-core#53]
Using the coordinates of a new plugin that  was installed locally using "mvn install", the 
plugin shows up in the list with the "danger triangle" icon, but no error message appears in the message pane.

**Comment by johann-petrak** [comment]
Oops, this happend with 8.5 release, wanted to test it on master actually.

**Comment by johann-petrak** [comment]
OK could get loaded without problems with GATE 8.6-SNAPSHOT, commit 23f56424000e89cbe6d100d8a5a4dd09f3278e1d 

The plugin uses gate-plugin-base 8.5.1.

But no matter what the error or problem is, there should be a message on the message pane.

**Comment by greenwoodma** [comment]
Because you've used plugin-base 8.5.1 it won't load into 8.5 by design - plugin. Is valid() will return false. I agree though we probably need a message somewhere as to why.

**Comment by johann-petrak** [comment]
Yes, I mentioned the reason so it is easier to reproduce this, if necessary, but the issue is about not having a message.

**Comment by greenwoodma** [comment]
Indeed. There are a while bunch of things that isValid will hide from the user probably without producing an error message, so hopefully the issue will help us improve other situations where the same thing can happen
