### ISSUE TITLE
Serializing JAPE Transducer: error when loading a grammar with imports outside of gate package

### ISSUE THREAD

**Issue by thomas-heitz** [GateNLP/gate-core#58]
Version used:
GATE 8.4.1 build 5753 / Java 1.8.0_181 Oracle Corporation on Linux amd64 4.9.0-5-amd64.

I didn't find any correction or issue related to this problem.

The serialization is very useful for obfuscating Gate grammars when used in a commercial environment.
https://gate.ac.uk/sale/tao/splitch8.html#sec:jape:serialization

Thanks for any help,

-- 
Thomas Heitz

When reloading a grammar like Jape or Jape Plus that uses imports outside of gate package,

for example:
Imports: {
import java.text.Normalizer;
}

the following error occurs:

gate.creole.ResourceInstantiationException: java.util.zip.ZipException: Not in GZIP format
	at gate.jape.plus.Transducer.init(Transducer.java:640)
	at gate.Factory.createResource(Factory.java:432)
	at gate.gui.NewResourceDialog$4.run(NewResourceDialog.java:270)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at gate.jape.plus.Transducer.init(Transducer.java:624)
	... 3 more

**Comment by greenwoodma** [comment]
I've just tried and I can't reproduce this. I've tried with both Jape and Jape+ using the following file

```Imports: {
import java.text.Normalizer;
}

Phase:	TestPhase
Input: Token
Options: control = appelt

Rule: Test
({Token})
-->
{}
```

And I can serialise and reload it using both PRs without problems. The only difference is I'm using 8.5.1 rather than 8.4, but I can't see why that would make any difference here. 

I do, however, get exactly that error if I try and pass a normal JAPE file in as the binaryGrammarURL. Any chance you accidentally did that?

**Comment by greenwoodma** [comment]
@thomas-heitz it appears you aren't listed as a watcher for this issue so just wanted to make sure you would see my reply.

**Comment by thomas-heitz** [comment]
After lots of tries, I finally found that I was trying to reload a binary Jape grammar as a binary Jape Plus grammar...

I've mixed Jape and Jape Plus grammar in my application, big mistake.

So I close the issue.

Really sorry for this.

**Comment by greenwoodma** [comment]
Glad it's sorted.
