### ISSUE TITLE
Upgrade Tika dependency to latest (1.2)

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-core#66]
Change the Tika dependency to the most recent version, 1.20

(see also #65)

**Comment by greenwoodma** [comment]
(daft question but why open a duplicate issue)

**Comment by johann-petrak** [comment]
#65 is not really about upgrading Tika and may get solved or not once we upgrade. 
The immediate solution to the problem described there may well be what you initially suggested there. 
Also, wanted to open this to track any problems that may creep up once we test the upgraded core with other plugins.

**Comment by greenwoodma** [comment]
true I suppose, it's been a long day, just ignore me

**Comment by johann-petrak** [comment]
OK so turns out the following three libraries need to get removed from the excluded list in order to make 
the unit tests pass:
* org.ccil.cowan.tagsoup/tagsoup
* com.adobe.xmp/xmpcore 
* com.drewnoakes/metadata-extractor

**Comment by johann-petrak** [comment]
This breaks the gate-top build with error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:3.4:descriptor (default-descriptor) on project gate-maven-plugin: Execution default-descriptor of goal org.apache.maven.plugins:maven-plugin-plugin:3.4:descriptor failed.: IllegalArgumentException -> [Help 1]
```

Upgrading the version of the maven-plugin-plugin from 3.3 to 3.5 in gate-top/gate-maven-plugin/pom.xml seems to make that work again.

**Comment by johann-petrak** [comment]
Lets call this fixed then and open a specific issue if any problem arises because of this.
