### ISSUE TITLE
Plugin upgrade utility should allow to upgrade any version/version ranges

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-core#75]
When one has many pipelines in a project/directory tree it would be useful if the tsv file 
could be edited to allow a plugin get upgraded to a specific version, no matter what version it currently has (or, less importantly if the version is from within a range).
So a line like this or similar:

```
creole://uk.ac.gate.plugins;stringannotation;/ UPGRADE uk.ac.gate.plugins  stringannotation  4.1
```

(empty version number) would upgrade *any* version of the stringannotation plugin. 

This is especially useful because I think it is not too easy to actually find out which versions of which plugins are actually used in all those pipeline files. As far as I know we do not have a script to grep those out easily.

**Comment by greenwoodma** [comment]
Makes sense, although I think I'd go with a * or some other placeholder rather than just leaving the version blank

**Comment by ianroberts** [comment]
I went with Mark's `*` suggestion:

```
creole://uk.ac.gate.plugins;stringannotation;*/ UPGRADE uk.ac.gate.plugins  stringannotation  4.1
```
