### ISSUE TITLE
gate.bat fails when spaces in path

### ISSUE THREAD

**Issue by greenwoodma** [GateNLP/gate-core#84]
I haven't investigated this much, but when trying to use gate.bat during FIG12 I got an error about a file not found where it was only reporting up to a space in the path. We probably just need an extra set of quotes somewhere.... and a windows machine on which to test the fix!

**Comment by ianroberts** [comment]
Or just remove the `.bat` file altogether as all it does is delegate to the `.exe`.

**Comment by greenwoodma** [comment]
Makes sense. I hadn't actually got as far as looking inside the `.bat` file to see what it did!

One question though... is there anyway to start GATE on windows from a console and see error messages? I was trying to debug an issue where the splash screen flashed up and then the JVM exited. With the `gate.exe` run from the console you don't see any errors. My hope had been the `.bat` would do that but I'm guessing not

**Comment by ianroberts** [comment]
Only really by doing `java -jar gateLauncher.jar` by hand from a CMD prompt, but that won't pull in the settings from `gate.l4j.ini`.  There is an option `--l4j-debug` that you can pass to `gate.exe` but I'm not sure if that actually captures the Java stdout or just the launch4j mechanics prior to launching `javaw`

**Comment by greenwoodma** [comment]
right, and of course it's the fact that is uses `javaw` which means there is no chance of getting the logs out on the console. Will just remove the `.bat` file as cleanup

**Comment by greenwoodma** [comment]
closed by 9c599953c99ebf8ff55013ec4d958889ae1b50a1
