### ISSUE TITLE
GUI didn't show after run Main.java

### ISSUE THREAD

**Issue by fishzhuanlan** [GateNLP/gate-core#95]
After downloading the latest code run Main.java not show the GUI.
Debug the code it blocked at two place:
 1.  gate.gui.LogArea.java  Line:158   System.setOut(new UTF8PrintStream(out, true));
 2. gate.gui.MainFrame.java  method 
     public static Icon getIcon(String baseName, ClassLoader classloader)

  below line will blocked when the  svgName  is not correct for example: all characters lowercase

   Class<Icon> clazz = (Class<Icon>)Class.forName("gate.resources.img.svg." + svgName + "Icon", true, classloader);

**Comment by greenwoodma** [comment]
Could you provide a few more details on exactly how you are running GATE, i.e. using the supplied startup scripts or through an IDE or some other way. Plus which version of GATE, which operating system and version, which java version the contents of gate.l4j.ini, etc.

GATE is used by hundreds if not thousands of users and it almost all cases the GUI loads without issue, so my guess is there is something odd with your setup. I certainly can't see any reason why the two lines you reference would cause an issue if GATE is run in the normal way.

**Comment by greenwoodma** [comment]
Closed due to lack of follow up
